# Generated by Django 5.2.4 on 2025-07-28 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('report_type', models.CharField(choices=[('trips', 'Relatório de Viagens'), ('fuel', 'Relatório de Combustível'), ('services', 'Relatório de Serviços'), ('location', 'Relatório de Localização'), ('alerts', 'Relatório de Alertas')], max_length=20, verbose_name='Tipo de Relatório')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('fields', models.JSONField(help_text='Lista dos campos a serem incluídos no relatório', verbose_name='Campos do Relatório')),
                ('filters', models.JSONField(blank=True, help_text='Filtros padrão para o relatório', null=True, verbose_name='Filtros Padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatórios',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel')], max_length=10, verbose_name='Formato')),
                ('status', models.CharField(choices=[('generating', 'Gerando'), ('completed', 'Concluído'), ('failed', 'Falha')], default='generating', max_length=15, verbose_name='Status')),
                ('filters_used', models.JSONField(blank=True, null=True, verbose_name='Filtros Utilizados')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Caminho do Arquivo')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (bytes)')),
                ('records_count', models.IntegerField(blank=True, null=True, verbose_name='Número de Registros')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Relatório Gerado',
                'verbose_name_plural': 'Relatórios Gerados',
                'ordering': ['-generated_at'],
            },
        ),
    ]
