# Generated by Django 5.2.4 on 2025-07-28 09:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cor')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasolina'), ('diesel', 'Diesel'), ('electric', 'Elétrico'), ('hybrid', 'Híbrido')], default='gasoline', max_length=10, verbose_name='Tipo de Combustível')),
                ('fuel_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidade do Tanque (L)')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('maintenance', 'Manutenção')], default='active', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Motorista Designado')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200, verbose_name='Origem')),
                ('destination', models.CharField(max_length=200, verbose_name='Destino')),
                ('planned_start_time', models.DateTimeField(verbose_name='Horário Planejado de Início')),
                ('planned_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Horário Planejado de Fim')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Horário Real de Início')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Horário Real de Fim')),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='planned', max_length=15, verbose_name='Status')),
                ('distance_km', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distância (km)')),
                ('fuel_consumed', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Combustível Consumido (L)')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Propósito da Viagem')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-planned_start_time'],
            },
        ),
        migrations.CreateModel(
            name='TrackingDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True, verbose_name='ID do Dispositivo')),
                ('device_type', models.CharField(choices=[('coban_gps303f', 'Coban GPS303-F'), ('other', 'Outro')], default='coban_gps303f', max_length=20, verbose_name='Tipo do Dispositivo')),
                ('imei', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='IMEI')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('error', 'Erro')], default='active', max_length=10, verbose_name='Status')),
                ('last_communication', models.DateTimeField(blank=True, null=True, verbose_name='Última Comunicação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_device', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Dispositivo de Rastreamento',
                'verbose_name_plural': 'Dispositivos de Rastreamento',
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('maintenance', 'Manutenção Preventiva'), ('repair', 'Reparo'), ('inspection', 'Inspeção'), ('tire_change', 'Troca de Pneus'), ('oil_change', 'Troca de Óleo'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Serviço')),
                ('date', models.DateTimeField(verbose_name='Data do Serviço')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo (MZN)')),
                ('service_provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prestador de Serviço')),
                ('odometer_reading', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leitura do Odômetro (km)')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Próximo Serviço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Registro de Serviço',
                'verbose_name_plural': 'Registros de Serviços',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data do Abastecimento')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade (L)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo (MZN)')),
                ('odometer_reading', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Leitura do Odômetro (km)')),
                ('fuel_station', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posto de Combustível')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Registro de Combustível',
                'verbose_name_plural': 'Registros de Combustível',
                'ordering': ['-date'],
            },
        ),
    ]
