# Generated by Django 5.2.4 on 2025-07-28 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Área')),
                ('area_type', models.CharField(choices=[('allowed', 'Área Permitida'), ('restricted', 'Área Restrita'), ('depot', 'Depósito'), ('fuel_station', 'Posto de Combustível'), ('service_center', 'Centro de Serviço')], max_length=20, verbose_name='Tipo da Área')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('coordinates', models.JSONField(help_text='Array de coordenadas [lat, lng] definindo o polígono', verbose_name='Coordenadas')),
                ('radius', models.FloatField(blank=True, help_text='Para áreas circulares', null=True, verbose_name='Raio (metros)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicles', models.ManyToManyField(blank=True, related_name='geofence_areas', to='vehicles.vehicle', verbose_name='Veículos Monitorados')),
            ],
            options={
                'verbose_name': 'Área de Geofence',
                'verbose_name_plural': 'Áreas de Geofence',
            },
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude (m)')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='Velocidade (km/h)')),
                ('heading', models.FloatField(blank=True, null=True, verbose_name='Direção (graus)')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Precisão (m)')),
                ('timestamp', models.DateTimeField(verbose_name='Data/Hora')),
                ('ignition', models.BooleanField(default=False, verbose_name='Ignição Ligada')),
                ('engine_running', models.BooleanField(default=False, verbose_name='Motor Funcionando')),
                ('fuel_level', models.FloatField(blank=True, null=True, verbose_name='Nível de Combustível (%)')),
                ('battery_voltage', models.FloatField(blank=True, null=True, verbose_name='Voltagem da Bateria (V)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperatura (°C)')),
                ('odometer', models.FloatField(blank=True, null=True, verbose_name='Odômetro (km)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_data', to='vehicles.trackingdevice', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Dados de Localização',
                'verbose_name_plural': 'Dados de Localização',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('entered', 'Entrada na Área'), ('exited', 'Saída da Área'), ('violation', 'Violação de Área')], max_length=20, verbose_name='Tipo de Alerta')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('acknowledged', 'Reconhecido'), ('resolved', 'Resolvido')], default='active', max_length=15, verbose_name='Status')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Reconhecido por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_alerts', to='vehicles.vehicle', verbose_name='Veículo')),
                ('geofence_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracking.geofencearea', verbose_name='Área de Geofence')),
                ('location_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.locationdata', verbose_name='Dados de Localização')),
            ],
            options={
                'verbose_name': 'Alerta de Geofence',
                'verbose_name_plural': 'Alertas de Geofence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('scheduled', 'Manutenção Agendada'), ('overdue', 'Manutenção Vencida'), ('mileage', 'Quilometragem Atingida'), ('fuel_low', 'Combustível Baixo'), ('battery_low', 'Bateria Baixa'), ('engine_fault', 'Falha no Motor')], max_length=20, verbose_name='Tipo de Alerta')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('acknowledged', 'Reconhecido'), ('resolved', 'Resolvido')], default='active', max_length=15, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_maintenance_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Reconhecido por')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_alerts', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Alerta de Manutenção',
                'verbose_name_plural': 'Alertas de Manutenção',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_limit', models.FloatField(verbose_name='Limite de Velocidade (km/h)')),
                ('actual_speed', models.FloatField(verbose_name='Velocidade Registrada (km/h)')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('acknowledged', 'Reconhecido'), ('resolved', 'Resolvido')], default='active', max_length=15, verbose_name='Status')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_speed_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Reconhecido por')),
                ('location_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.locationdata', verbose_name='Dados de Localização')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_alerts', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Alerta de Velocidade',
                'verbose_name_plural': 'Alertas de Velocidade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='locationdata',
            index=models.Index(fields=['device', '-timestamp'], name='tracking_lo_device__8e78eb_idx'),
        ),
        migrations.AddIndex(
            model_name='locationdata',
            index=models.Index(fields=['timestamp'], name='tracking_lo_timesta_b7e871_idx'),
        ),
        migrations.AddIndex(
            model_name='locationdata',
            index=models.Index(fields=['latitude', 'longitude'], name='tracking_lo_latitud_a1d3f4_idx'),
        ),
    ]
